Cmqat 348/honghaejin
29CM-Developers/test-automation pull request #210
Opened 2023-12-14 03:57 UTC by haejinhong-29cm

실패 부분 수정
쿠폰 시나리오 수정
주문관련 내용수정

2023-12-14 04:41 UTC, hyunjunpark-29cm requested changes

2023-12-14 04:41 UTC, hyunjunpark-29cm commented on android_automation/page_action/cart_page.py
> +            total_order_amount_title = aal(wd, '//*[@id="__next"]/div/section[2]/dl/dt[2]')
이것 /dt 배열값 없이 /dt 로만 끝나도 되는지 한번 확인해주세요~
된다면 수정해주시고 안된다면 다른 방법을 찾아주세요. 
이제 깨지기 쉬운 계층 구조는 코드리뷰에서 리젝하겠습니다

2023-12-14 04:41 UTC, hyunjunpark-29cm commented on android_automation/page_action/my_coupon_page.py
> +                         f'//androidx.drawerlayout.widget.DrawerLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/andro
앞으로는 절대 xpath 사용시 리젝하겠습니다. 상대 xpath 사용할 수 있는 방법을 고민해주세요

2023-12-14 04:41 UTC, hyunjunpark-29cm commented on android_automation/page_action/product_detail_page.py
> +                                    f'//androidx.drawerlayout.widget.DrawerLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[2]/android.v
앞으로는 절대 xpath 사용시 리젝하겠습니다. 상대 xpath 사용할 수 있는 방법을 고민해주세요

2023-12-14 04:41 UTC, hyunjunpark-29cm commented on android_automation/test_cases/home_test.py
> +                                  '//androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[5]')
앞으로는 절대 xpath 사용시 리젝하겠습니다. 상대 xpath 사용할 수 있는 방법을 고민해주세요

2023-12-14 05:29 UTC, dajeongjeong-29cm commented on android_automation/test_cases/payment_test.py
> +            delivery_order_page.check_order_cancel(wd)
warning을 제거하고 exception 발생 시, except Exception에 에러 메세지를 append 하는 코드를 추가해주셔야 합니다.
해당 코드가 추가되어야 slack noti에서 어떠한 사유로 실패했는지 확인이 가능합니다.

`error_texts.append(values_control.find_next_value(error_text, 'Exception'))`

2023-12-14 06:46 UTC, haejinhong-29cm commented on android_automation/page_action/my_coupon_page.py
> +                         f'//androidx.drawerlayout.widget.DrawerLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/andro
네 확인하여 상대 xpath로 수정했습니다.

2023-12-14 06:46 UTC, haejinhong-29cm commented on android_automation/page_action/product_detail_page.py
> +                                    f'//androidx.drawerlayout.widget.DrawerLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[2]/android.v
네 확인하여 상대 xpath로 수정했습니다.

2023-12-14 06:46 UTC, haejinhong-29cm commented on android_automation/test_cases/home_test.py
> +                                  '//androidx.compose.ui.platform.ComposeView/android.view.View/android.view.View/android.view.View[5]')
네 확인하여 상대 xpath로 수정했습니다.

2023-12-14 06:47 UTC, haejinhong-29cm commented on android_automation/test_cases/payment_test.py
> +            delivery_order_page.check_order_cancel(wd)
넵 추가했습니다. 다정님 일부 기존 test_result 남아있는 부분은 해당 코드 미추가된 상태고 변경 시에 같이 추가로 적용하겠습니다. 확인 감사합니다.

2023-12-14 06:57 UTC, haejinhong-29cm commented on android_automation/page_action/cart_page.py
> +            total_order_amount_title = aal(wd, '//*[@id="__next"]/div/section[2]/dl/dt[2]')
넵 수정했습니다.

2023-12-14 07:13 UTC, hyunjunpark-29cm requested changes

2023-12-14 07:13 UTC, hyunjunpark-29cm commented on android_automation/page_action/my_coupon_page.py
> +            coupon = aal(coupon_layer_item, '//android.view.View/android.view.View/android.widget.TextView[4]')
이곳도 절대 xpath 네요

2023-12-14 07:13 UTC, hyunjunpark-29cm commented on android_automation/test_cases/home_test.py
> +                                  '//android.view.View/android.view.View/android.view.View[@index=4]')
```suggestion
                                  '//android.view.View[@index=4]')
```
이렇게 해도 찾아질 것 같은데 한번 해보시겠어요? 계층 구조는 길면 길수록 깨지기 쉽습니다

2023-12-15 00:27 UTC, haejinhong-29cm commented on android_automation/test_cases/home_test.py
> +                                  '//android.view.View/android.view.View/android.view.View[@index=4]')
넵 전달 주신 코드로도 동작하여 해당 코드로 수정했습니다. 감사합니다.

2023-12-15 00:28 UTC, haejinhong-29cm commented on android_automation/page_action/my_coupon_page.py
> +            coupon = aal(coupon_layer_item, '//android.view.View/android.view.View/android.widget.TextView[4]')
다른 xpath 로 변경했습니다.

2023-12-15 00:29 UTC, haejinhong-29cm commented on android_automation/page_action/product_detail_page.py
> +                                    f'//androidx.drawerlayout.widget.DrawerLayout/android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[2]/android.v
넵 해당 부분 수정하였고 다음부터 절대 xpath 사용 지양하도록 하겠습니다

2023-12-15 00:57 UTC, hyunjunpark-29cm approved these changes

2023-12-15 01:02 UTC, dajeongjeong-29cm commented on android_automation/page_action/order_page.py
> +    # 앱에서 웹뷰로 전환
요거 change_webview_contexts 안쓰시고 코드로 작성하신 이유가 있으신걸까요?? 🤔

2023-12-15 01:03 UTC, dajeongjeong-29cm approved these changes

2023-12-15 01:07 UTC, haejinhong-29cm commented on android_automation/page_action/order_page.py
> +    # 앱에서 웹뷰로 전환
아네 어제 확인한 바로는 공통 메소드는 핸들러까지 바꿔주고 있는데 해당 화면은 핸들러를 바꿔주면 동작하지 않더라구요.. 그래서 핸들러를 스위치 하지 않는 내부 메소드로 했습니다.

2023-12-15 01:07 UTC, merged